# Exercício:

## 01 – Cite três vantagens do uso das funções e duas características que toda função deva ter?

R.: Vantagens: processamento mais eficiente, coreção de erros global, organização do código, usabilidade. Deve conter apenas uma única tarefa, deve retornar apenas um valor e deve ser curta, direta e pequena.

## Responda a pergunta do exercício 2 da aula 10, usando funções:<br>
Instancie um objeto da classe NumPy array, contendo 5 valores quantitativos randômicos normalmente distribuídos, com média 10 e desvio padrão 3.<br><br>
Quantos e quais são os valores superiores a 10?

## 02 – Descreva o racional da sua resposta:

R.: Primeiro precisamos instanciar este objeto contendo os valores segundo os requisitos do exercício. Usando uma estrutura condicional para cada valor no array, definimos uma função que verifica se o valor é superior à 10, em caso positivo, imprimimos o valor e incrementamos o contador. Em caso negativo não fazemos nada. Ao final o número de valores superiores a 10 é impresso.

## 03 – Desenhe o fluxograma da resposta:

<img src="./img/12-fluxograma_exercício3.png" width="800" />

## 04 – Escreva o programa em Python:

In [1]:
import numpy as np

In [2]:
# Instânciando o objeto array do numpy
array_randomico = np.random.normal(loc=10, scale=3, size=5)
array_randomico

array([13.2381149 , 11.36904404,  6.82452869,  9.71142606,  9.96308625])

In [3]:
# Número de valores são superiores a 10
superior_a_10 = 0
alvo = 10
if array_randomico[0] > alvo:
    print(f"O valor {array_randomico[0]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[1] > alvo:
    print(f"O valor {array_randomico[1]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[2] > alvo:
    print(f"O valor {array_randomico[2]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[3] > alvo:
    print(f"O valor {array_randomico[3]} é superior a {alvo}")
    superior_a_10 += 1
if array_randomico[4] > alvo:
    print(f"O valor {array_randomico[4]} é superior a {alvo}")
    superior_a_10 += 1
print(f"O número de valores superiores a {alvo} é: {superior_a_10}")

O valor 13.23811489543403 é superior a 10
O valor 11.3690440366219 é superior a 10
O número de valores superiores a 10 é: 2


In [4]:
def verificar_superior_a_10(array: np.array, alvo: int = 10) -> None:
    ''' 
    Verifica quais elementos do array são
    superiores a um valor alvo e conta quantos são.
        Parâmetros:
            array (np.array): O array a ser verificado.
            alvo (int): O valor de referência para comparação (padrão é 10).
        Retorna:
            None: A função apenas imprime os resultados,
                    não retorna nenhum valor.
    '''
    superior_a_10 = 0
    for elemento in array:
        if elemento > alvo:
            print(f"O valor {elemento} é superior a {alvo}")
            superior_a_10 += 1
    print(f"O número de valores superiores a {alvo} é: {superior_a_10}")
    return None

In [5]:
help(verificar_superior_a_10)

Help on function verificar_superior_a_10 in module __main__:

verificar_superior_a_10(array: <built-in function array>, alvo: int = 10) -> None
    Verifica quais elementos do array são
    superiores a um valor alvo e conta quantos são.
        Parâmetros:
            array (np.array): O array a ser verificado.
            alvo (int): O valor de referência para comparação (padrão é 10).
        Retorna:
            None: A função apenas imprime os resultados,
                    não retorna nenhum valor.



In [6]:
verificar_superior_a_10(array=array_randomico)

O valor 13.23811489543403 é superior a 10
O valor 11.3690440366219 é superior a 10
O número de valores superiores a 10 é: 2


## 05 – Seria possível, com o racional proposto, saber quantos e quais valores são superiores a 20? Porque?

In [7]:
verificar_superior_a_10(array=array_randomico, alvo=20)

O número de valores superiores a 20 é: 0


## Desenvolva um programa de computador que retorne a média de um conjunto de valores.

## 06 – Descreva o racional da sua resposta:

R.: Declaração de objetos com valores. A função receberá estes valores, usando argumentos como parâmetro, o que possibilita receber qualquer número de objetos. Na função, primeiro declaramos um objeto inteiro que receberá a soma dos itens recebidos. Estes serão então iterados, incrementando o objeto que soma os valores recebidos. O retorno da função será o valor da soma dividido pelo número de elementos.

## 07 – Desenhe o fluxograma da resposta:

<img src="./img/12-fluxograma_exercício7.png" width="1200" />

## 07 – Escreva o programa em Python:

In [8]:
def calcular_media_valores(*valores: int) -> float:
    '''
        Calcula a média de um conjunto de valores inteiros.
            Parâmetros:
                *valores (int): Um número variável de argumentos inteiros.
            Retorna:
                float: A média dos valores fornecidos.
    '''
    soma_valores = 0
    n_valores = 0
    for valor in valores:
        soma_valores += int(valor)
        n_valores += 1
    media = soma_valores / n_valores
    return media

In [9]:
help(calcular_media_valores)

Help on function calcular_media_valores in module __main__:

calcular_media_valores(*valores: int) -> float
    Calcula a média de um conjunto de valores inteiros.
        Parâmetros:
            *valores (int): Um número variável de argumentos inteiros.
        Retorna:
            float: A média dos valores fornecidos.



In [10]:
calcular_media_valores(10, 20, 30)

20.0

In [11]:
calcular_media_valores("10", 20, 30)

20.0

## 09 – Desenvolva um programa de computador que retorne a divisão de dois objetos simples. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [12]:
def verificar_tipos_simples(objeto: int | float) -> bool:
    '''
        Verifica se os objetos fornecidos são do tipo numpy.ndarray,
        pandas.Series e pandas.DataFrame.
            Parâmetros:
                objetos (int | float): Um objeto simples a serem verificado.
            Retorna:
                bool: True se todos os objetos forem do tipo esperado, 
                    False caso contrário.
    '''
    tipo_int = type(objeto) == int
    tipo_float = type(objeto) == float
    
    if tipo_int or tipo_float:
        print(f"O objeto {objeto} é do tipo esperado.")
        return True
    else:
        print(f"O objeto {objeto} não é do tipo esperado.")
        return False

In [13]:
help(verificar_tipos_simples)

Help on function verificar_tipos_simples in module __main__:

verificar_tipos_simples(objeto: int | float) -> bool
    Verifica se os objetos fornecidos são do tipo numpy.ndarray,
    pandas.Series e pandas.DataFrame.
        Parâmetros:
            objetos (int | float): Um objeto simples a serem verificado.
        Retorna:
            bool: True se todos os objetos forem do tipo esperado, 
                False caso contrário.



In [14]:
array_1 = np.random.normal(loc=10, scale=3, size=(5, 3))
array_2 = np.random.normal(loc=10, scale=3, size=(5, 3))
type(array_2)

numpy.ndarray

In [15]:
import pandas as pd

In [16]:
serie_1 = pd.Series(array_1[0])
serie_2 = pd.Series(array_2[1])
type(serie_1)

pandas.core.series.Series

In [17]:
df_1 = pd.DataFrame(data=array_1, columns=['A', 'B', 'C'])
df_2 = pd.DataFrame(data=array_2, columns=['A', 'B', 'C'])
type(df_1)

pandas.core.frame.DataFrame

In [18]:
objetos = {
    "array_1": array_1,
    "array_2": array_2,
    "serie_1": serie_1,
    "serie_2": serie_2,
    "df_1": df_1,
    "df_2": df_2,
    "string": f"{serie_1.iloc[0]}",
    "inteiro": int(serie_1.iloc[0]),
    "float": array_1[0, 0],
    "lista": list(array_1[0]),
    "tuple": tuple(array_1[0]),
    "set": set(array_1[0]),
}
objetos

{'array_1': array([[ 9.94165997, 14.36880555, 11.84945572],
        [11.19786148, 10.69486327,  9.97386052],
        [ 9.80619829,  4.25434226,  8.24152397],
        [13.4889797 , 12.78579145, 11.50853363],
        [ 6.73777926, 12.30709723, 12.61956983]]),
 'array_2': array([[17.45403   , 13.30673459, 11.84826396],
        [12.4508361 ,  4.65135245,  8.58431896],
        [10.46446804, 13.04299188,  8.72004677],
        [ 5.07438196, 13.56055472, 12.18951691],
        [ 8.28646489,  3.69662929,  7.58110707]]),
 'serie_1': 0     9.941660
 1    14.368806
 2    11.849456
 dtype: float64,
 'serie_2': 0    12.450836
 1     4.651352
 2     8.584319
 dtype: float64,
 'df_1':            A          B          C
 0   9.941660  14.368806  11.849456
 1  11.197861  10.694863   9.973861
 2   9.806198   4.254342   8.241524
 3  13.488980  12.785791  11.508534
 4   6.737779  12.307097  12.619570,
 'df_2':            A          B          C
 0  17.454030  13.306735  11.848264
 1  12.450836   4.651352   

In [19]:
for tipo, objeto in enumerate(objetos.items()):
    print("-"*10)
    print(f"{objeto[0]} - {verificar_tipos_simples(objeto[1])}")

----------
O objeto [[ 9.94165997 14.36880555 11.84945572]
 [11.19786148 10.69486327  9.97386052]
 [ 9.80619829  4.25434226  8.24152397]
 [13.4889797  12.78579145 11.50853363]
 [ 6.73777926 12.30709723 12.61956983]] não é do tipo esperado.
array_1 - False
----------
O objeto [[17.45403    13.30673459 11.84826396]
 [12.4508361   4.65135245  8.58431896]
 [10.46446804 13.04299188  8.72004677]
 [ 5.07438196 13.56055472 12.18951691]
 [ 8.28646489  3.69662929  7.58110707]] não é do tipo esperado.
array_2 - False
----------
O objeto 0     9.941660
1    14.368806
2    11.849456
dtype: float64 não é do tipo esperado.
serie_1 - False
----------
O objeto 0    12.450836
1     4.651352
2     8.584319
dtype: float64 não é do tipo esperado.
serie_2 - False
----------
O objeto            A          B          C
0   9.941660  14.368806  11.849456
1  11.197861  10.694863   9.973861
2   9.806198   4.254342   8.241524
3  13.488980  12.785791  11.508534
4   6.737779  12.307097  12.619570 não é do tipo espe

In [20]:
def dividir_valores_simples(num1: int | float, num2: int | float) -> float:
    '''
        Realiza a divisão de dois números, tratando a divisão por zero.
            Parâmetros:
                num1 (int | float): O numerador da divisão.
                num2 (int | float): O denominador da divisão.
            Retorna:
                float: O resultado da divisão se num2 for diferente de zero,
                    ou uma mensagem de erro caso contrário.
    '''
    if num2 == 0:
        print("Erro: Divisão por zero não é permitida.")
        return None
    else:
        if verificar_tipos_simples(num1) and verificar_tipos_simples(num2):
            resultado = num1 / num2
            print(f"O resultado da divisão de {num1} por {num2} é: {resultado}")
            return resultado
        else:
            print("Erro: Ambos os números devem ser do tipo int ou float.")
            return None

In [21]:
help(dividir_valores_simples)

Help on function dividir_valores_simples in module __main__:

dividir_valores_simples(num1: int | float, num2: int | float) -> float
    Realiza a divisão de dois números, tratando a divisão por zero.
        Parâmetros:
            num1 (int | float): O numerador da divisão.
            num2 (int | float): O denominador da divisão.
        Retorna:
            float: O resultado da divisão se num2 for diferente de zero,
                ou uma mensagem de erro caso contrário.



In [22]:
teste_divisao = {
    "int/int": (40, 2),
    "float/float": (40.0, 2.0),
    "int/float": (40, 2.0),
    "float/int": (40.0, 2),
    "erro_1": (40, 0),
    "erro_2": ([40], 2),
    "erro_3": ([40], [2]),
    "erro_4": (40, [2]),
}
teste_divisao

{'int/int': (40, 2),
 'float/float': (40.0, 2.0),
 'int/float': (40, 2.0),
 'float/int': (40.0, 2),
 'erro_1': (40, 0),
 'erro_2': ([40], 2),
 'erro_3': ([40], [2]),
 'erro_4': (40, [2])}

In [23]:
for k, v in teste_divisao.items():
    print("-"*10)
    print(f"{k}")
    dividir_valores_simples(v[0], v[1])

----------
int/int
O objeto 40 é do tipo esperado.
O objeto 2 é do tipo esperado.
O resultado da divisão de 40 por 2 é: 20.0
----------
float/float
O objeto 40.0 é do tipo esperado.
O objeto 2.0 é do tipo esperado.
O resultado da divisão de 40.0 por 2.0 é: 20.0
----------
int/float
O objeto 40 é do tipo esperado.
O objeto 2.0 é do tipo esperado.
O resultado da divisão de 40 por 2.0 é: 20.0
----------
float/int
O objeto 40.0 é do tipo esperado.
O objeto 2 é do tipo esperado.
O resultado da divisão de 40.0 por 2 é: 20.0
----------
erro_1
Erro: Divisão por zero não é permitida.
----------
erro_2
O objeto [40] não é do tipo esperado.
Erro: Ambos os números devem ser do tipo int ou float.
----------
erro_3
O objeto [40] não é do tipo esperado.
Erro: Ambos os números devem ser do tipo int ou float.
----------
erro_4
O objeto 40 é do tipo esperado.
O objeto [2] não é do tipo esperado.
Erro: Ambos os números devem ser do tipo int ou float.


## 10 – Desenvolva um programa de computador que retorne a divisão de dois objetos compostos. Seu programa deve ser capaz de reconhecer a classe destes objetos e o valor, antes de retornar ao usuário.

In [24]:
def verificar_tipos_compostos(
        objeto: np.ndarray | pd.Series | pd.DataFrame) -> bool:
    '''
        Verifica se os objetos fornecidos são do tipo numpy.ndarray,
        pandas.Series e pandas.DataFrame.
            Parâmetros:
                objetos (list): Uma lista de objetos a serem verificados.
            Retorna:
                bool: True se todos os objetos forem do tipo esperado, 
                    False caso contrário.
    '''
    tipo_array = type(objeto) == np.ndarray
    tipo_serie = type(objeto) == pd.Series
    tipo_frame = type(objeto) == pd.DataFrame
    
    if tipo_array or tipo_serie or tipo_frame:
        print("O objeto é do tipo esperado.")
        return True
    else:
        print("O objeto não é do tipo esperado.")
        return False

In [25]:
help(verificar_tipos_compostos)

Help on function verificar_tipos_compostos in module __main__:

verificar_tipos_compostos(objeto: numpy.ndarray | pandas.core.series.Series | pandas.core.frame.DataFrame) -> bool
    Verifica se os objetos fornecidos são do tipo numpy.ndarray,
    pandas.Series e pandas.DataFrame.
        Parâmetros:
            objetos (list): Uma lista de objetos a serem verificados.
        Retorna:
            bool: True se todos os objetos forem do tipo esperado, 
                False caso contrário.



In [26]:
for tipo, objeto in enumerate(objetos.items()):
    print("-"*10)
    print(f"{objeto[0]} - {verificar_tipos_compostos(objeto[1])}")

----------
O objeto é do tipo esperado.
array_1 - True
----------
O objeto é do tipo esperado.
array_2 - True
----------
O objeto é do tipo esperado.
serie_1 - True
----------
O objeto é do tipo esperado.
serie_2 - True
----------
O objeto é do tipo esperado.
df_1 - True
----------
O objeto é do tipo esperado.
df_2 - True
----------
O objeto não é do tipo esperado.
string - False
----------
O objeto não é do tipo esperado.
inteiro - False
----------
O objeto não é do tipo esperado.
float - False
----------
O objeto não é do tipo esperado.
lista - False
----------
O objeto não é do tipo esperado.
tuple - False
----------
O objeto não é do tipo esperado.
set - False


In [27]:
def dividir_valores_compostos(
        comp1: np.ndarray | pd.Series | pd.DataFrame,
        comp2: np.ndarray | pd.Series | pd.DataFrame) -> float:
    '''
        Realiza a divisão de dois números, tratando a divisão por zero.
            Parâmetros:
                comp1 (np.ndarray | pd.Series | pd.DataFrame): O numerador da divisão.
                comp2 (np.ndarray | pd.Series | pd.DataFrame): O denominador da divisão.
            Retorna:
                float: O resultado da divisão se comp2 for diferente de zero,
                    ou uma mensagem de erro caso contrário.
    '''
    if verificar_tipos_compostos(comp1) and verificar_tipos_compostos(comp2):
        resultado = comp1 / comp2
        print(f"O resultado da divisão de {comp1} por {comp2} é: {resultado}")
        return resultado
    else:
        print("Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.")
        return None

In [28]:
help(verificar_tipos_compostos)

Help on function verificar_tipos_compostos in module __main__:

verificar_tipos_compostos(objeto: numpy.ndarray | pandas.core.series.Series | pandas.core.frame.DataFrame) -> bool
    Verifica se os objetos fornecidos são do tipo numpy.ndarray,
    pandas.Series e pandas.DataFrame.
        Parâmetros:
            objetos (list): Uma lista de objetos a serem verificados.
        Retorna:
            bool: True se todos os objetos forem do tipo esperado, 
                False caso contrário.



In [31]:
teste_divisao = {
    "int/int": (40, 2),
    "float/float": (40.0, 2.0),
    "int/float": (40, 2.0),
    "float/int": (40.0, 2),
    "erro_1": (40, 0),
    "erro_2": (np.array([40]), 2),
    "erro_3": (40, np.array([2])),
    "array": (np.array([40]), np.array([2])),
    "dataframe": (pd.DataFrame([40]), pd.DataFrame([2])),
    "series": (pd.Series([40]), pd.Series([2])),
}
teste_divisao

{'int/int': (40, 2),
 'float/float': (40.0, 2.0),
 'int/float': (40, 2.0),
 'float/int': (40.0, 2),
 'erro_1': (40, 0),
 'erro_2': (array([40]), 2),
 'erro_3': (40, array([2])),
 'array': (array([40]), array([2])),
 'dataframe': (    0
  0  40,
     0
  0  2),
 'series': (0    40
  dtype: int64,
  0    2
  dtype: int64)}

In [32]:
for k, v in teste_divisao.items():
    print("-"*10)
    print(f"{k}")
    dividir_valores_compostos(v[0], v[1])

----------
int/int
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
float/float
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
int/float
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
float/int
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
erro_1
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
erro_2
O objeto é do tipo esperado.
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
erro_3
O objeto não é do tipo esperado.
Erro: Ambos os números devem ser do tipo array, Series ou DataFrame.
----------
array
O objeto é do tipo esperado.
O objeto é do tipo esperado.
O resultado da divisão de [40] por [2] é: [2