In [13]:
a = 2
b = 3
c = 4
print(f"{a} == {b}: {a == b}")
print(f"{a} != {b}: {a != b}")
print(f"{a} > {b}: {a > b}")
print(f"{a} >= {b}: {a > b}")
print(f"{a} < {b}: {a < b}")
print(f"{a} <= {b}: {a < b}")
print(f"{a} <= {b} < {c}: {a <= b < c}")

2 == 3: False
2 != 3: True
2 > 3: False
2 >= 3: False
2 < 3: True
2 <= 3: True
2 <= 3 < 4: True


In [14]:
a = 2
b = 3.5
c = 4
print(f"{a} == {b}: {a == b}")
print(f"{a} != {b}: {a != b}")
print(f"{a} > {b}: {a > b}")
print(f"{a} >= {b}: {a > b}")
print(f"{a} < {b}: {a < b}")
print(f"{a} <= {b}: {a < b}")
print(f"{a} <= {b} < {c}: {a <= b < c}")

2 == 3.5: False
2 != 3.5: True
2 > 3.5: False
2 >= 3.5: False
2 < 3.5: True
2 <= 3.5: True
2 <= 3.5 < 4: True


In [15]:
a = 1
b = False
c = 4
print(f"{a} == {b}: {a == b}")
print(f"{a} != {b}: {a != b}")
print(f"{a} > {b}: {a > b}")
print(f"{a} >= {b}: {a > b}")
print(f"{a} < {b}: {a < b}")
print(f"{a} <= {b}: {a < b}")
print(f"{a} <= {b} < {c}: {a <= b < c}")

1 == False: False
1 != False: True
1 > False: True
1 >= False: True
1 < False: False
1 <= False: False
1 <= False < 4: False


In [16]:
obj_tupla_int = (1, 0, 1, 0)
obj_tupla_bool = (True, False, True, False)
print(f"{obj_tupla_int} == {obj_tupla_bool}: {obj_tupla_int == obj_tupla_bool}")
print(f"{obj_tupla_int} != {obj_tupla_bool}: {obj_tupla_int != obj_tupla_bool}")
print(f"{obj_tupla_int} > {obj_tupla_bool}: {obj_tupla_int > obj_tupla_bool}")
print(f"{obj_tupla_int} >= {obj_tupla_bool}: {obj_tupla_int > obj_tupla_bool}")
print(f"{obj_tupla_int} < {obj_tupla_bool}: {obj_tupla_int < obj_tupla_bool}")
print(f"{obj_tupla_int} <= {obj_tupla_bool}: {obj_tupla_int < obj_tupla_bool}")

(1, 0, 1, 0) == (True, False, True, False): True
(1, 0, 1, 0) != (True, False, True, False): False
(1, 0, 1, 0) > (True, False, True, False): False
(1, 0, 1, 0) >= (True, False, True, False): False
(1, 0, 1, 0) < (True, False, True, False): False
(1, 0, 1, 0) <= (True, False, True, False): False


In [22]:
obj_tupla_int = (1, 0, 1, 0)
obj_list_bool = [True, False, True, False]
print(f"{obj_tupla_int} == {obj_list_bool}: {obj_tupla_int == obj_list_bool}")
print(f"{obj_tupla_int} != {obj_list_bool}: {obj_tupla_int != obj_list_bool}")
print(f"{obj_tupla_int} > {obj_list_bool}: {obj_tupla_int > obj_list_bool}")
print(f"{obj_tupla_int} >= {obj_list_bool}: {obj_tupla_int > obj_list_bool}")
print(f"{obj_tupla_int} < {obj_list_bool}: {obj_tupla_int < obj_list_bool}")
print(f"{obj_tupla_int} <= {obj_list_bool}: {obj_tupla_int < obj_list_bool}")

(1, 0, 1, 0) == [True, False, True, False]: False
(1, 0, 1, 0) != [True, False, True, False]: True


TypeError: '>' not supported between instances of 'tuple' and 'list'

In [23]:
obj_list_int = [1, 0, 1, 0]
obj_list_bool = [True, False, True, False]
print(f"{obj_list_int} == {obj_list_bool}: {obj_list_int == obj_list_bool}")
print(f"{obj_list_int} != {obj_list_bool}: {obj_list_int != obj_list_bool}")
print(f"{obj_list_int} > {obj_list_bool}: {obj_list_int > obj_list_bool}")
print(f"{obj_list_int} >= {obj_list_bool}: {obj_list_int > obj_list_bool}")
print(f"{obj_list_int} < {obj_list_bool}: {obj_list_int < obj_list_bool}")
print(f"{obj_list_int} <= {obj_list_bool}: {obj_list_int < obj_list_bool}")

[1, 0, 1, 0] == [True, False, True, False]: True
[1, 0, 1, 0] != [True, False, True, False]: False
[1, 0, 1, 0] > [True, False, True, False]: False
[1, 0, 1, 0] >= [True, False, True, False]: False
[1, 0, 1, 0] < [True, False, True, False]: False
[1, 0, 1, 0] <= [True, False, True, False]: False


In [24]:
obj_dict_int = {0: 1, 1: 0, 2: 1, 3: 0}
obj_dict_bool = {0: True, 1: False, 2: True, 3: False}
print(f"{obj_dict_int} == {obj_dict_bool}: {obj_dict_int == obj_dict_bool}")
print(f"{obj_dict_int} != {obj_dict_bool}: {obj_dict_int != obj_dict_bool}")
print(f"{obj_dict_int} > {obj_dict_bool}: {obj_dict_int > obj_dict_bool}")
print(f"{obj_dict_int} >= {obj_dict_bool}: {obj_dict_int > obj_dict_bool}")
print(f"{obj_dict_int} < {obj_dict_bool}: {obj_dict_int < obj_dict_bool}")
print(f"{obj_dict_int} <= {obj_dict_bool}: {obj_dict_int < obj_dict_bool}")

{0: 1, 1: 0, 2: 1, 3: 0} == {0: True, 1: False, 2: True, 3: False}: True
{0: 1, 1: 0, 2: 1, 3: 0} != {0: True, 1: False, 2: True, 3: False}: False


TypeError: '>' not supported between instances of 'dict' and 'dict'

In [20]:
import numpy as np

In [25]:
obj_array_int = np.array([1, 0, 1, 0])
obj_array_bool = np.array([True, False, True, False])
print(f"{obj_array_int} == {obj_array_bool}: {obj_array_int == obj_array_bool}")
print(f"{obj_array_int} != {obj_array_bool}: {obj_array_int != obj_array_bool}")
print(f"{obj_array_int} > {obj_array_bool}: {obj_array_int > obj_array_bool}")
print(f"{obj_array_int} >= {obj_array_bool}: {obj_array_int > obj_array_bool}")
print(f"{obj_array_int} < {obj_array_bool}: {obj_array_int < obj_array_bool}")
print(f"{obj_array_int} <= {obj_array_bool}: {obj_array_int < obj_array_bool}")

[1 0 1 0] == [ True False  True False]: [ True  True  True  True]
[1 0 1 0] != [ True False  True False]: [False False False False]
[1 0 1 0] > [ True False  True False]: [False False False False]
[1 0 1 0] >= [ True False  True False]: [False False False False]
[1 0 1 0] < [ True False  True False]: [False False False False]
[1 0 1 0] <= [ True False  True False]: [False False False False]


In [26]:
import pandas as pd

In [29]:
obj_pandas_int = pd.Series([1, 0, 1, 0])
obj_pandas_bool = pd.Series([True, False, True, False])

print("-" * 40)
print(f"{obj_pandas_int == obj_pandas_bool}")
print("-" * 40)
print(f"{obj_pandas_int != obj_pandas_bool}")
print("-" * 40)
print(f"{obj_pandas_int > obj_pandas_bool}")
print("-" * 40)
print(f"{obj_pandas_int > obj_pandas_bool}")
print("-" * 40)
print(f"{obj_pandas_int < obj_pandas_bool}")
print("-" * 40)
print(f"{obj_pandas_int < obj_pandas_bool}")

----------------------------------------
0    True
1    True
2    True
3    True
dtype: bool
----------------------------------------
0    False
1    False
2    False
3    False
dtype: bool
----------------------------------------
0    False
1    False
2    False
3    False
dtype: bool
----------------------------------------
0    False
1    False
2    False
3    False
dtype: bool
----------------------------------------
0    False
1    False
2    False
3    False
dtype: bool
----------------------------------------
0    False
1    False
2    False
3    False
dtype: bool
